trigger:
  batch: true
  branches:
    include:
    - 'master'
steps:
- task: Npm@1
  displayName: 'NPM Clean'
  inputs:
    command: custom
    workingDir: '$(Build.BinariesDirectory)'
    verbose: false
    customCommand: run clean
- task: Npm@1
  displayName: 'NPM Build'
  inputs:
    command: custom
    workingDir: '$(Build.BinariesDirectory)'
    verbose: false
    customCommand: run build
- task: ArchiveFiles@2
  displayName: Archive
  inputs:
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    verbose: true
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    azureSubscription: Azure
    WebAppName: 'Creeper-Bot'
    enableCustomDeployment: true
    ExcludeFilesFromAppDataFlag: false