trigger:
  batch: true
  branches:
    include:
    - 'master'

pool:
  vmImage: 'windows-latest'

jobs:
- job: Release
  condition: 
    and(succeeded(),
        in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'))
  steps:
  - task: Npm@1
    displayName: 'NPM Install'
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)'
  - task: Npm@1
    displayName: 'NPM Clean'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run clean'
  - task: Npm@1
    displayName: 'NPM Build'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run build'
  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      verbose: true
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure'
      appType: 'webApp'
      WebAppName: 'Creeper-Bot'
      deployToSlotOrASE: true
      ResourceGroupName: 'Creeper-Bot'
      SlotName: 'production'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      enableCustomDeployment: true
      DeploymentType: 'webDeploy'
      RemoveAdditionalFilesFlag: true