pr: none
trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: Release
  steps:
  - task: Npm@1
    displayName: 'NPM Install'
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)'
  - task: Npm@1
    displayName: 'NPM Clean'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run clean'
  - task: Npm@1
    displayName: 'NPM Build'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run build'
  - task: ArchiveFiles@2
  - task: CopyFiles@2
    displayName: 'Copy Compiled Files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
          **\*.js
          Web.config
          package.json
          node_modules\**\*.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Create Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Release'
      publishLocation: 'Container'